core/urls.py
from django.urls import path
from .views import (item_list, product, checkout, add_to_cart,
remove_from_cart, order_summary,add_single_item,remove_single_item, order_done)

app_name = 'core'

urlpatterns = [
    path('', item_list, name = 'item-list'),
    path('product/<int:pk>', product, name = 'product'),
    path('order-summary', order_summary, name = 'order-summary'),
    path('add-to-cart/<int:pk>', add_to_cart, name = 'add-to-cart'),
    path('add-single-item/<int:pk>', add_single_item, name = 'add-single-item'),
    path('remove-single-item/<int:pk>', remove_single_item, name = 'remove-single-item'),
    path('remove-from-cart/<int:pk>', remove_from_cart, name = 'remove-from-cart'),
    path('order-done/<int:pk>', order_done, name = 'order-done'),
    path('checkout', checkout, name = 'checkout')
]

templates/base.html
{% load static %}
{% load cart_template_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
      html,
      body,
      header,
      .carousel {
        height: 60vh;
      }
  
      @media (max-width: 740px) {
  
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }
  
      @media (min-width: 800px) and (max-width: 850px) {
  
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }
  
    </style>
</head>
<body>
      <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light white mb-4">
        <div class="container">
    
          <!-- Brand -->
          <a class="navbar-brand waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">
            <strong class="blue-text">Shop</strong>
          </a>
    
          <!-- Collapse -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
            <!-- Left -->
            <ul class="navbar-nav mr-auto">
              <li class="nav-item {% if request.resolver_match.url_name == 'item-list' %}active{% endif %}">
                <a class="nav-link waves-effect" href="{% url 'core:item-list'%}">Home
                </a>
              </li>
            </ul>
    
            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
              <li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'core:order-summary'%}">
                  <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                  <i class="fas fa-shopping-cart"></i>
                  <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                </a>
              </li>
              <li class="nav-item">
                <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li class="nav-item">
                <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="nav-item">
                <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="nav-link border border-light rounded waves-effect"
                  target="_blank">
                  <i class="fab fa-github mr-2"></i>MDB GitHub
                </a>
              </li>
            </ul>
    
          </div>
    
        </div>
      </nav>
      <!-- Navbar -->
      <div class="mt-5 pt-4">
          {% if messages %}
              {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% endfor %}
          {% endif %}
          </div>
    {% block content  %}
    {% endblock content %}
    <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

        <!--Call to action-->
        <div class="pt-4">
          <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
            role="button">Download MDB
            <i class="fas fa-download ml-2"></i>
          </a>
          <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
            free tutorial
            <i class="fas fa-graduation-cap ml-2"></i>
          </a>
        </div>
        <!--/.Call to action-->
    
        <hr class="my-4">
    
        <!-- Social icons -->
        <div class="pb-4">
          <a href="https://www.facebook.com/mdbootstrap" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
          </a>
    
          <a href="https://twitter.com/MDBootstrap" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
          </a>
    
          <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
            <i class="fab fa-youtube mr-3"></i>
          </a>
    
          <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
            <i class="fab fa-google-plus-g mr-3"></i>
          </a>
    
          <a href="https://dribbble.com/mdbootstrap" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
          </a>
    
          <a href="https://pinterest.com/mdbootstrap" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
          </a>
    
          <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
            <i class="fab fa-github mr-3"></i>
          </a>
    
          <a href="http://codepen.io/mdbootstrap/" target="_blank">
            <i class="fab fa-codepen mr-3"></i>
          </a>
        </div>
        <!-- Social icons -->
    
        <!--Copyright-->
        <div class="footer-copyright py-3">
          © 2019 Copyright:
          <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
        </div>
        <!--/.Copyright-->
    
      </footer>
      <!--/.Footer-->
     <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %} "></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content  %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      
      <!--Grid row-->
      <div class="row">
          
        <div class="col-md-3"></div>
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card content-->
            <form method = 'POST' class="card-body">
                {% csrf_token %}
              <!--email-->
              <div class="md-form mb-5">
                <!-- <input type="text" id="email" class="form-control" placeholder="youremail@example.com"> -->
                {{ form.email }}
                <label for="email" class="">Email (optional)</label>
              </div>

              <!--address-->
              <div class="md-form mb-5">
                <!-- <input type="text" id="address" class="form-control" placeholder="1234 Main St"> -->
                {{ form.address }}
                <label for="address" class="">Address</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.country}}
                  <!-- <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                  </select> -->
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  <!-- <input type="text" class="form-control" id="zip" placeholder="" required> -->
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>
              <div class=" custom-checkbox">
                {{ form.use_for_next_time}}
                <label class="" for="save-info">Save this information for next time</label>
              </div>

              <hr>
              <div class="d-block my-3">
              {% for value, name in form.fields.payment_method.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_method" value="{{ value }}" type="radio" class="custom-control-input" checked >
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                  {% endfor %}
            </div>
                <!-- <div class="custom-control custom-radio">
                  <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="paypal">Paypal</label>
              </div> -->
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->
        <div class="col-md-3"></div>
      </div>
      <!--Grid row-->

    </div>
    
  </main>
  <!--Main layout-->
  {% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content  %}
  <!--Main layout-->
  <main>
    <div class="container">
      <!--Section: Products v.3-->
      
      <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow ">
          {% for item in items %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card">

              <!--Card image-->
              {% if item.image %}
              <div class="view overlay">
                <img src="{{ item.image.url}}" class="card-img-top"
                  alt="">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              {% endif %}
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{item.name}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{item.title}}
                      <span class="badge badge-pill danger-color">{{item.tag}}</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>{{item.price}}$</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}
        </div>
        <!--Grid row-->
      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if items.has_other_pages %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if items.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page={{ items.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Previous</span>
                </a>
              </li>
          {% endif %}
          {% for i in items.paginator.page_range%}
          {% if i == items.number %}
          <li class="page-item active">
            <a class="page-link">{{ i }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% else %}
          <li class="page-item ">
              <a class="page-link" href="?page={{ i }}">{{i}}
                <span class="sr-only">(current)</span>
              </a>
            </li>
          {% endif %}
          {% endfor %}
          {% if items.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ items.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}

    </div>
  </main>
  <!--Main layout-->
  {% endblock content %}
 

templates/item_list.html
{% extends 'base.html' %}

{% block content  %}
<h2>Here is list of items</h2>
{% for item in items %}
    {{ item }}
{% endfor %}
{% endblock content %}

templates/order-done.html
{% extends 'base.html' %}

{% block content  %}
<a class='btn btn-primary ' href="{% url 'core:order-done' order.id %}">Order Done for Id {{ order.id}} </a>
{% endblock content %}

templates/order-summry.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in order.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{order_item.item.title}}</td>
            <td>{{order_item.item.price}}$</td>
            <td>
                <a href="{% url 'core:remove-single-item' order_item.item.id %}"><i class="fas fa-minus mr-2"></i></a>
                {{order_item.quantity}}
                <a href="{% url 'core:add-single-item' order_item.item.id %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
                {% if order_item.get_discount_price %}
                {{order_item.get_discount_price}}$
                <span class="badge badge-primary">Saving ${{ order_item.get_save_amount }}</span>
                {% else %}
                {{order_item.get_item_total_price}}$
                </a>
                {% endif %}
                <a style='color: red;' href="#">
                     <i class="fas fa-trash float-right"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{order.get_final_price}}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href="{% url 'core:checkout' %}">Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/product.html
{% extends 'base.html' %}
{% block content  %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{item.image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{item.name}}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">{{item.tag}}</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              {% if item.discount_price %}
              <span class="mr-1">
                <del>${{item.price}}</del>
              </span>
              <span>${{ item.discount_price}}</span>
              {% else %}
              <span>${{ item.price}}</span>
              {% endif %}

            </p>

            <p class="lead font-weight-bold">{{item.title}}</p>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa
              sint voluptatibus!
              Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>

            <form class="d-flex justify-content-left">
              <a href="{{ item.add_to_cart }}"
               class="btn btn-success btn-md my-0 p"> Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              <a href="{{ item.remove_from_cart }}" class="btn btn-danger btn-md my-0 p" >Remove from cart
                  <i class="fas fa-shopping-cart ml-1"></i>
              </a>
            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
  {% endblock content %}